### ISSUE TITLE
Stack size exceeded

### ISSUE THREAD

**Issue by Samar029** [loebi-ch/jquery-clock-timepicker#53]
I am trying clock-timepicker first it worked well but after a few week i again check now it shows an error:
Uncaught RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at F (jquery.min.js:2:29722)
    at Function.style (jquery.min.js:2:53566)
    at jquery.min.js:2:55477
    at R (jquery.min.js:2:29542)
    at ce.fn.init.css (jquery.min.js:2:55327)
    at J (jquery-clock-timepicker.min.js:1:23542)
    at Q (jquery-clock-timepicker.min.js:1:24351)
    at HTMLInputElement.e (jquery-clock-timepicker.min.js:1:11534)
    at HTMLInputElement.dispatch (jquery.min.js:2:39997)

I am trying to resolve this issue but no luck.

**Comment by loebi-ch** [comment]
There is somewhere a recursion problem. Use the non minified JavaScript jquery-clock-timepicker.js and see again in the console for the error message. This leads you nearer to the root case...

**Comment by loebi-ch** [comment]
I stopped the development of this component because it depends on jQuery.

The new component https://www.npmjs.com/package/clock-timepicker has no dependencies at all and is a massive improvement over this component.

Therefore I close this issue.
